configName: pic32mz_ef_sk_freertos
folderName: ''
format_version: v1.0
frameworkPath: D:\11_Repo\01_H3\h3
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: audio;azure-rtos-threadx;azure_rtos;bsp;core;core_apps_sam_d5x_e5x;crypto;csp;dev_packs;dummy_package;gfx;net;net_apps_pic32mx;net_apps_pic32mz;net_apps_sam_9x60;net_apps_sam_a5d2;net_apps_sam_e5x;net_apps_sam_e70_v71;net_apps_sam_rh71;quick_docs;touch;usb;wireless;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFH144.atdf
