format_version: v1.0
configName: pic32mz_das_sk
folderName: pic32mz_das_sk
frameworkPath: C:\harmony\h3
processor: PIC32MZ2064DAS169
projectName: pic32mz_das_sk
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAS169.atdf
