format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipTcp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_TCP_DISABLE_CRYPTO_USAGE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: 'TCPIP_TCP_DISABLE_CRYPTO_USAGE '}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_TCP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipTcp, value: '16360'}
- type: Attachments
  children:
  - type: GenericDependency
    attributes: {id: Tcp_Crypto_Dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: tcpipTcp}
