format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_spi}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: DRV_SPI_ASYNC_HEADER_LOCAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: DRV_SPI_ASYNC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Combo
    attributes: {id: DRV_SPI_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi, value: Synchronous}
      - type: User
        attributes: {value: Asynchronous}
  - type: File
    attributes: {id: DRV_SPI_SYNC_HEADER_LOCAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: DRV_SPI_SYNC_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_spi}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_SPI_MODE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: Asynchronous}
      - type: String
        attributes: {id: DRV_SPI_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: SPI1}
      - type: Integer
        attributes: {id: DRV_SPI_QUEUE_SIZE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: '10'}
      - type: Integer
        attributes: {id: DRV_SPI_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: '-1'}
      - type: Integer
        attributes: {id: DRV_SPI_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: '-1'}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: drv_spi}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: TCP/IP STACK}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: 'DRIVER LAYER:drvExtMacEnc28j60_0:ENC28J60_SPI'}
      - type: DirectDependency
        attributes: {id: drv_spi_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: spi1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SPI1_SPI}
- type: ElementPosition
  attributes: {x: '275', y: '359', id: drv_spi}
