configName: pic32mz_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFM144
projectName: ''
settings:
  PackageFilter: bsp;core;crypto;cryptoauthlib;crypto_for_4.8.1;csp;csp_apps_sam_9x60;csp_apps_sam_a5d2;Devices;dev_packs;h3_token_manager;harmony-services;net;net_10base_t1s;net_apps_pic32cz_ca;net_apps_pic32mx;net_apps_pic32mz;net_apps_sam_9x60;net_apps_sam_a5d2;net_apps_sam_a5d2_3.7.0;net_apps_sam_a7g5;net_apps_sam_e5x;net_apps_sam_e70_v71;net_apps_sam_rh71;quick_docs;usb;wireless;wireless_wifi;x2c;zzz_expresslogic_threadx
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFM144.atdf
