format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_FS_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'true'}
  - type: Boolean
    attributes: {id: SYS_FS_IDX1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'true'}
  - type: Boolean
    attributes: {id: SYS_FS_IDX2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'false'}
  - type: Boolean
    attributes: {id: SYS_FS_IDX3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: 'false'}
  - type: Integer
    attributes: {id: SYS_FS_INSTANCES_NUMBER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: SYS_FS_MAX_FILES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '25'}
  - type: Integer
    attributes: {id: SYS_FS_MAX_FILE_SYSTEM_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: SYS_FS_MPFS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: SYS_FS_MPFS_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SYS_FS_MPFS_LOCAL_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SYS_FS_MPFS_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: SYS_FS_TOTAL_VOLUMES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: '2'}
  - type: Integer
    attributes: {id: SYS_FS_VOLUME_NUMBER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: drv_sdmmc_0, targetAttachmentID: drv_media}
      - type: TargetAttachment
        attributes: {targetComponentID: drv_memory_0, targetAttachmentID: drv_media}
- type: ElementPosition
  attributes: {x: '387', y: '340', id: sys_fs}
