configName: pic32mz_ef_sk_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: aws_cloud;azure_rtos;bootloader;bsp;core;core_apps_pic32cz_ca;crypto;csp;csp_apps_pic32cz_ca;csp_apps_sam_9x60;Devices;dev_packs;ethercat;harmony-services;net;net_apps_pic32cz_ca;net_apps_pic32cz_ca_backup;net_apps_pic32mx;net_apps_pic32mx_notworking;net_apps_pic32mz;net_apps_sam_9x60;net_apps_sam_a5d2;net_apps_sam_e5x;net_apps_sam_e70_v71;quick_docs;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFH144.atdf
