format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MZ_DA_Starter_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '320', y: '19', id: BSP_PIC32MZ_DA_Starter_Kit}
