format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipDhcpServer}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_DHCPS_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcpServer, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_DHCPS_INTERFACE_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcpServer, value: '1'}
  - type: Integer
    attributes: {id: TCPIP_DHCP_SERVER_V2_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDhcpServer, value: '2924'}
- type: ElementPosition
  attributes: {x: '550', y: '140', id: tcpipDhcpServer}
