format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipArp}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_ARP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipArp, value: '222'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: tcpipArp}
