format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipFtps}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_FTPS_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipFtps, value: '0'}
- type: ElementPosition
  attributes: {x: '710', y: '260', id: tcpipFtps}
