format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipHttpNet}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_HTTP_NET_CUSTOM_TEMPLATE_SL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttpNet, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_HTTP_NET_FILE_UPLOAD_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_FILE_UPLOAD_NAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttpNet, value: '4944'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_LISTEN_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '443'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_MPFS_NVM_NUM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_MPFS_NVM_PATH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_MPFS_NVM_VOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_SSI_VARIABLE_STRING_MAX_LENGTH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
- type: ElementPosition
  attributes: {x: '378', y: '148', id: tcpipHttpNet}
