format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipDnss}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_DNSS_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipDnss, value: '264'}
- type: ElementPosition
  attributes: {x: '190', y: '240', id: tcpipDnss}
