format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipFtps}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_FTPS_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipFtps, value: '0'}
  - type: String
    attributes: {id: TCPIP_FTP_MOUNT_POINT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: /mnt/mchpDrive1/}
- type: ElementPosition
  attributes: {x: '170', y: '60', id: tcpipFtps}
