format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipSnmp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_SNMP_CUSTOM_TEMPLATE_SL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipSnmp, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_SNMP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipSnmp, value: '120'}
- type: ElementPosition
  attributes: {x: '610', y: '140', id: tcpipSnmp}
