format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipUdp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_UDP_COMMANDS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '298', y: '20', id: tcpipUdp}
