format_version: v1.0
type: GroupComponent
attributes: {displayName: TCP/IP STACK, id: TCP/IP STACK}
children:
- type: ElementPosition
  attributes: {x: '524', y: '432', id: TCP/IP STACK}
- type: Attachments
  children:
  - type: Attachment
    attributes: {namespace: PRESENTATION LAYER, id: 'net_Pres:Net_Pres_Crypto_Dependency'}
  - type: Attachment
    attributes: {namespace: BASIC CONFIGURATION, id: 'tcpipStack:Core_SysConsole_Dependency'}
