format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MZ_EF_Starter_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '339', y: '24', id: BSP_PIC32MZ_EF_Starter_Kit}
