format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: FREERTOS_TOTAL_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '88000'}
- type: ElementPosition
  attributes: {x: '740', y: '20', id: FreeRTOS}
