format_version: v1.0
type: GeneratorComponent
attributes: {id: tcpipNetConfig}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: TCPIP_MAC_BRIDGE_ADV_SETTING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_DCPT_POOL_REPLENISH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_DCPT_POOL_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_ENTRY_TIMEOUT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_MAC_BRIDGE_EVENT_NOTIFY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_MAC_BRIDGE_FDB_ENTRY_EXISTS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_FDB_TABLE_ENTRIES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_MAC_BRIDGE_IF_NAME_TABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_MAX_PORTS_NO}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_MAX_TRANSIT_DELAY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_MAC_BRIDGE_NO_DYNAMIC_LEARN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_PACKET_POOL_REPLENISH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_PACKET_POOL_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_PACKET_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_MAC_BRIDGE_STATISTICS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_MAC_BRIDGE_TASK_RATE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_MAC_BRIDGE_COMMANDS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_MAC_BRIDGE_DISABLE_GLUE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_STACK_NETWORK_INTERAFCE_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipNetConfig, value: '2'}
  - type: Menu
    attributes: {id: TCPIP_STACK_NETWORK_MAC_BRIDGE_CONFIG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_STACK_NETWORK_MAC_BRIDGE_COUNT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipNetConfig, value: '2'}
  - type: Boolean
    attributes: {id: TCPIP_STACK_USE_MAC_BRIDGE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipNetConfig, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: tcpipNetConfig}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_DNS_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 192.168.100.1}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_GATEWAY_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 192.168.100.1}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_HOST_NAME_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: MCHPENCX24_E}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_INTERFACE_NAME_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: ENCX24J600}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_IP_ADDRESS_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 192.168.100.12}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_MAC_DRIVER_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: DRV_ENCX24J600_MACObject}
      - type: Boolean
        attributes: {id: TCPIP_NETWORK_MACBRIDGE_ADD_IDX0}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
        - type: Values
          children:
          - type: User
            attributes: {value: 'true'}
      - type: Boolean
        attributes: {id: TCPIP_STACK_NETWORK_CONFIG_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: 'true'}
      - type: Integer
        attributes: {id: TCPIP_STACK_NETWORK_CONFIG_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_0, value: '0'}
  - type: InstanceComponent
    attributes: {instance: '1', id: tcpipNetConfig}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_DNS_IDX1}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: 192.168.100.1}
          - type: User
            attributes: {value: 192.168.100.1}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_GATEWAY_IDX1}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: 192.168.100.1}
          - type: User
            attributes: {value: 192.168.100.1}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_HOST_NAME_IDX1}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: MCHPBOARD_E}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_INTERFACE_NAME_IDX1}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: ETHMAC}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_IP_ADDRESS_IDX1}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: 192.168.100.10}
          - type: User
            attributes: {value: 192.168.100.10}
      - type: String
        attributes: {id: TCPIP_NETWORK_DEFAULT_MAC_DRIVER_IDX1}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: DRV_ETHMAC_PIC32MACObject}
      - type: Boolean
        attributes: {id: TCPIP_NETWORK_MACBRIDGE_ADD_IDX1}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: 'true'}
      - type: Boolean
        attributes: {id: TCPIP_STACK_NETWORK_CONFIG_IDX1}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: 'true'}
      - type: Integer
        attributes: {id: TCPIP_STACK_NETWORK_CONFIG_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: tcpipNetConfig_1, value: '1'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: NETCONFIG_MAC_Dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drvPic32mEthmac}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: libdrvPic32mEthmac}
- type: ElementPosition
  attributes: {x: '420', y: '20', id: tcpipNetConfig}
